-- Supabase SQL schema for Library Attendance System

-- Books table
create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  shelf integer not null check (shelf > 0),
  available boolean not null default true,
  isbn text null,
  photo_url text null,
  description text null,
  created_at timestamptz not null default now()
);

-- Students table
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  lrn text not null unique,
  name text not null,
  year_level text not null,
  section text not null,
  created_at timestamptz not null default now()
);

-- Attendance table
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  check_in timestamptz not null default now(),
  check_out timestamptz null,
  created_at timestamptz not null default now()
);

-- Convenience view for recent activity
create or replace view public.attendance_view as
select 
  a.id,
  case when a.check_out is null then 'in' else 'out' end as type,
  s.name as user,
  (case when a.check_out is null then 'Checked in' else 'Checked out' end) as action,
  coalesce(a.check_out, a.check_in) as time,
  case when a.check_out is not null then age(a.check_out, a.check_in) end as duration
from public.attendance a
join public.students s on s.id = a.student_id;

-- Function to compute average stay time in seconds
create or replace function public.attendance_avg_stay_seconds()
returns table(avg_seconds numeric)
language sql
as $$
  select avg(extract(epoch from (check_out - check_in))) as avg_seconds
  from public.attendance
  where check_out is not null;
$$;

-- Enable RLS but allow anon read/write for prototype (tighten later)
alter table public.books enable row level security;
alter table public.students enable row level security;
alter table public.attendance enable row level security;

do $$
begin
  -- Books policies
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'books' and policyname = 'books_anon_all'
  ) then
    create policy books_anon_all on public.books for all using (true) with check (true);
  end if;

  -- Students policies
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'students' and policyname = 'students_anon_all'
  ) then
    create policy students_anon_all on public.students for all using (true) with check (true);
  end if;

  -- Attendance policies
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'attendance' and policyname = 'attendance_anon_all'
  ) then
    create policy attendance_anon_all on public.attendance for all using (true) with check (true);
  end if;
end$$;



-- Auth helper RPCs (no public tables, only the auth.users table)
-- Returns total number of users in the auth table
create or replace function public.auth_user_count()
returns bigint
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  cnt bigint;
begin
  select count(*) into cnt from auth.users;
  return cnt;
end;
$$;

-- Returns true if there is at least one user with user_metadata.role = 'admin'
create or replace function public.has_admin()
returns boolean
language sql
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from auth.users u
    where coalesce(u.raw_user_meta_data->>'role', '') = 'admin'
  );
$$;

-- Returns number of users with role = 'admin'
create or replace function public.admin_count()
returns bigint
language sql
security definer
set search_path = public, auth
as $$
  select count(*)::bigint from auth.users u where coalesce(u.raw_user_meta_data->>'role','') = 'admin';
$$;

-- Allow anon/authenticated clients to execute these functions
grant execute on function public.auth_user_count() to anon, authenticated;
grant execute on function public.has_admin() to anon, authenticated;
grant execute on function public.admin_count() to anon, authenticated;

-- Storage bucket for book photos
-- Note: This needs to be run in Supabase dashboard or via CLI as it requires storage_admin role
-- Bucket name: book-photos
-- Public: true
-- Allowed MIME types: image/jpeg, image/png, image/gif, image/webp
-- File size limit: 5242880 (5MB)
-- 
-- Run this SQL in Supabase SQL editor or via CLI:
/*
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'book-photos',
  'book-photos',
  true,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp']
)
ON CONFLICT (id) DO NOTHING;

-- Storage policies for book-photos bucket
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT
USING (bucket_id = 'book-photos');

CREATE POLICY "Authenticated users can upload"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'book-photos' AND auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete"
ON storage.objects FOR DELETE
USING (bucket_id = 'book-photos' AND auth.role() = 'authenticated');
*/